# Generated by Django 3.1.3 on 2020-12-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='observaciones',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
