# Generated by Django 3.1.3 on 2020-12-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0002_auto_20201201_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
