# Generated by Django 3.1.3 on 2020-12-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0003_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
