# Generated by Django 3.1.3 on 2020-12-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometria', '0004_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
